"""Create tables users,foods,rooms,gyms

Revision ID: 9c96030749b6
Revises: e7055b520008
Create Date: 2023-07-04 23:12:03.706565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c96030749b6'
down_revision = 'e7055b520008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rooms_gym_id_gyms'), 'gyms', ['gym_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rooms_gym_id_gyms'), type_='foreignkey')
        batch_op.drop_column('gym_id')

    # ### end Alembic commands ###
