"""Create tables users,foods,rooms,gyms

Revision ID: 3e9c2085112e
Revises: f328b49dc008
Create Date: 2023-07-06 11:12:28.984482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c2085112e'
down_revision = 'f328b49dc008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
