"""Create tables users,foods,rooms,gyms

Revision ID: 9d6d2cbb0a5b
Revises: d076b94e7600
Create Date: 2023-07-06 11:07:11.818433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6d2cbb0a5b'
down_revision = 'd076b94e7600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
