"""Create tables users,foods,rooms,gyms

Revision ID: a8e5b120d3e0
Revises: 15c76a6ab60f
Create Date: 2023-07-06 10:54:20.171696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e5b120d3e0'
down_revision = '15c76a6ab60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
