"""Create tables users,foods,rooms,gyms

Revision ID: c0edcca7b012
Revises: 3e9c2085112e
Create Date: 2023-07-06 11:21:16.764040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0edcca7b012'
down_revision = '3e9c2085112e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
