"""Create tables users,foods,rooms,gyms

Revision ID: c3cb17671d51
Revises: c0edcca7b012
Create Date: 2023-07-06 11:24:15.429242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cb17671d51'
down_revision = 'c0edcca7b012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
