"""Create tables users,foods,rooms,gyms

Revision ID: d076b94e7600
Revises: eea30fdd558f
Create Date: 2023-07-06 11:06:44.881518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd076b94e7600'
down_revision = 'eea30fdd558f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
