"""Create tables users,foods,rooms,gyms

Revision ID: deb0b4d2cd82
Revises: f5202cd338db
Create Date: 2023-07-06 11:26:02.374098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb0b4d2cd82'
down_revision = 'f5202cd338db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
