"""Create tables users,foods,rooms,gyms

Revision ID: eea30fdd558f
Revises: a8e5b120d3e0
Create Date: 2023-07-06 11:01:17.275202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea30fdd558f'
down_revision = 'a8e5b120d3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
