"""Create tables users,foods,rooms,gyms

Revision ID: f328b49dc008
Revises: 9d6d2cbb0a5b
Create Date: 2023-07-06 11:10:22.239136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f328b49dc008'
down_revision = '9d6d2cbb0a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
