"""Create tables users,foods,rooms,gyms

Revision ID: f5202cd338db
Revises: c3cb17671d51
Create Date: 2023-07-06 11:25:23.234362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5202cd338db'
down_revision = 'c3cb17671d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
